name: create release

on:
  push:
    tags:
      - v*

  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        required: false
        description: 'Create release'

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          server-id: github
      - name: Configure Git user
        run: |
          git config user.email "no-mail"
          git config user.name "ig-deploy-bot"
      - name: Publish JAR
        run: ./mvnw -B release:prepare release:perform
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#    name: Release
#      uses: qcastel/github-actions-maven-release@TAG_NAME
#      with:
#        access-token: ${{ secrets.GITHUB_ACCESS_TOKEN }}
#        env:
#          JAVA_HOME: /usr/lib/jvm/java-11-openjdk/
#        git-release-bot-name: "ig-deploy-bot"
#        git-release-bot-email: "no-email"
#        release-branch-name: "main"
#        gpg-enabled: "false"

#  sync-branches:
#    runs-on: ubuntu-latest
#    needs: [ build ]
#    name: Syncing branches
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#      - name: Set up Node
#        uses: actions/setup-node@v1
#        with:
#          node-version: 12
#      - name: Opening pull request
#        id: pull
#        uses: tretuna/sync-branches@1.2.0
#        with:
#          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
#          FROM_BRANCH: "release"
#          TO_BRANCH: "main"